---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes
    
- name: "Install nodejs and npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes
    state: latest

- name: "Install pm2"
  become: yes
  apt:
    name: ["pm2"]
    global: yes
    production: yes
